# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BeMyEyes < Formula
  desc "A Terminal User Interface (TUI) for analyzing/ summarizing/ questioning / searching into videos using AI"
  homepage "https://github.com/fboucher/be-my-eyes"
  version "0.1.0"
  license "MIT"

  depends_on "sqlite"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fboucher/be-my-eyes/releases/download/v0.1.0/be-my-eyes_0.1.0_darwin_amd64.tar.gz"
      sha256 "b916c856b478fa97d16d66714217ac2dcc78c47f25bae0039a45cb9eb6341d71"

      def install
        bin.install "be-my-eyes"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fboucher/be-my-eyes/releases/download/v0.1.0/be-my-eyes_0.1.0_darwin_arm64.tar.gz"
      sha256 "4e1604b6ff8d74de3babdac3c64185f44ff2d900ad06d1a397ac38d57da32392"

      def install
        bin.install "be-my-eyes"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fboucher/be-my-eyes/releases/download/v0.1.0/be-my-eyes_0.1.0_linux_amd64.tar.gz"
      sha256 "38cd1617502295b6bd57ccc1386f8e7c40ad0ef64cbdfdf41118f92e846335fd"
      def install
        bin.install "be-my-eyes"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fboucher/be-my-eyes/releases/download/v0.1.0/be-my-eyes_0.1.0_linux_arm64.tar.gz"
      sha256 "41371bb6e9c615af83d45b1606a263f4ddf874531f5c8d71ea1b3a0c48f5db4f"
      def install
        bin.install "be-my-eyes"
      end
    end
  end

  test do
    system "#{bin}/be-my-eyes", "--version"
  end
end
