# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BeMyEyes < Formula
  desc "TUI for Reka Vision AI API"
  homepage "https://github.com/fboucher/be-my-eyes"
  version "0.0.32"
  license "MIT"

  depends_on "sqlite"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fboucher/be-my-eyes/releases/download/v0.0.32/be-my-eyes_0.0.32_darwin_amd64.tar.gz"
      sha256 "39aac0dea431995fdeb58468b0359c4f564d57f42c37f428b53a96651cafb261"

      def install
        bin.install "be-my-eyes"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fboucher/be-my-eyes/releases/download/v0.0.32/be-my-eyes_0.0.32_darwin_arm64.tar.gz"
      sha256 "0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5"

      def install
        bin.install "be-my-eyes"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fboucher/be-my-eyes/releases/download/v0.0.32/be-my-eyes_0.0.32_linux_amd64.tar.gz"
      sha256 "a52ed196b22310c0650a95b2858271e7da407918b13dd2db898d6c5c58728bea"
      def install
        bin.install "be-my-eyes"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fboucher/be-my-eyes/releases/download/v0.0.32/be-my-eyes_0.0.32_linux_arm64.tar.gz"
      sha256 "1e065338ab46b7c5a036a5fe3836f5247745c234613a1b78434daf71b731cbd1"
      def install
        bin.install "be-my-eyes"
      end
    end
  end

  test do
    system "#{bin}/be-my-eyes", "--version"
  end
end
